### ISSUE TITLE
Checklist mode is not implemented in Metanorma

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#199]
I think list items in checklist mode isn't implemented in Metanorma.

For example, in the following markup:
````
== Checklist sample

- [ ] Information System Manager
- [ ] Information Coordinator
- [ ] Incident Response Manager
- [ ] ISIRT Commander
- [ ] GIRO Standing Office
````
The respective outputs (ascciidoctor vs metanorma) are:

_Asciidoctor:_
![issue-asciidoc](https://user-images.githubusercontent.com/33627611/73845611-6418d800-47f9-11ea-865f-66da12246bb2.JPG)

_Metanorma (DOC):_ 
![issue-metanorma](https://user-images.githubusercontent.com/33627611/73845621-67ac5f00-47f9-11ea-82d1-78a37bf68852.JPG)

Sample file: 
[checklist-bug.zip](https://github.com/metanorma/metanorma-standoc/files/4159692/checklist-bug.zip)

**Comment by ronaldtse** [comment]
I think this raises a more generic issue about data input. We wish to generalize data input to accept ISO 8000 style of data (data requirements that a data instance needs to comply with).

**Comment by opoudjis** [comment]
The generic issue about ISO 8000 data entry will NOT be considered here, because nobody has provided me with any requirements or statement of ISO 8000.
